# Generated by Django 5.0.3 on 2025-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('wishlisted', 'Wishlisted'), ('visited', 'Visited'), ('favorite', 'Favorite')], default='wishlisted', max_length=20),
        ),
    ]
