# Generated by Django 5.0.3 on 2025-12-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pin_is_public_pin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('museum', 'Museum'), ('park', 'Park'), ('hotel', 'Hotel'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
