# Generated by Django 5.0.3 on 2025-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_pin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('trip', 'Trip'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('Attraction', 'Attraction'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
