# Generated by Django 5.0.3 on 2025-12-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_alter_pin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='description',
        ),
        migrations.AddField(
            model_name='pin',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
